version: "3.1"
services:

  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        PROJECT_NAME: ${PROJECT_NAME}
        DOMAIN: ${DOMAIN}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        SVN_USERNAME: ${SVN_USERNAME}
        SVN_PASSWORD: ${SVN_PASSWORD}
        ADMIN_USERNAME: ${ADMIN_USERNAME}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
    container_name: ${PROJECT_NAME}_django
    volumes:
      - docs:/www/readthedocs/public_web_root
    command: supervisord
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    container_name: ${PROJECT_NAME}_mysql
    restart: always
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${PROJECT_NAME}_db
      MYSQL_USER: ${PROJECT_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3306:3306"

volumes:
  database:
  docs:
