version: "3.1"

services:

  django:
    build:
      context: ./django
      args:
        SVN_USERNAME: ${SVN_USERNAME}
        SVN_PASSWORD: ${SVN_PASSWORD}
        ADMIN_USERNAME: ${ADMIN_USERNAME}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    container_name: ${PROJECT_NAME}_django
    command: supervisord
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    container_name: ${PROJECT_NAME}_mysql
    working_dir: /www/readthedocs
    volumes:
      - db:/www/readthedocs
    environment:
      - MYSQL_ROOT_PASSWORD=docker_root
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpw
    ports:
      - "8306:3306"

volumes:
  db: