version: "3.1"
services:

  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        SVN_USERNAME: ${SVN_USERNAME}
        SVN_PASSWORD: ${SVN_PASSWORD}
        ADMIN_USERNAME: ${ADMIN_USERNAME}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    container_name: ${PROJECT_NAME}_django
    command: supervisord
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - elasticsearch

  mysql:
    image: mysql:5.6
    container_name: ${PROJECT_NAME}_mysql
    restart: always
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker_root
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpw

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: ${PROJECT_NAME}_elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  database:
